// Expansions for the part-of-speech abbreviations Webster's 1913 uses.
// The map is keyed by the raw string as it appears in the entry JSON
// (whitespace and punctuation preserved). Anything not in the map renders
// without a tooltip.

const EXPANSIONS: Record<string, string> = {
  'n.': 'noun',
  'a.': 'adjective',
  'adj.': 'adjective',
  'adv.': 'adverb',
  'v.': 'verb',
  'v. t.': 'transitive verb',
  'v. i.': 'intransitive verb',
  'v. t. & i.': 'verb, transitive and intransitive',
  'v. i. & t.': 'verb, intransitive and transitive',
  'v. t. & n.': 'transitive verb and noun',
  'v. i. & n.': 'intransitive verb and noun',
  'v. & n.': 'verb and noun',
  'v. impers.': 'impersonal verb',
  'n. pl.': 'noun, plural',
  'n. sing.': 'noun, singular',
  'n. sing. & pl.': 'noun, singular and plural',
  'n. pl': 'noun, plural',
  'n. m.': 'noun, masculine',
  'n. f.': 'noun, feminine',
  'n. masc.': 'noun, masculine',
  'n. fem.': 'noun, feminine',
  'n. & v.': 'noun and verb',
  'n. & v. t.': 'noun and transitive verb',
  'n. & v. i.': 'noun and intransitive verb',
  'n. & a.': 'noun and adjective',
  'n. & adv.': 'noun and adverb',
  'n. & interj.': 'noun and interjection',
  'a. & n.': 'adjective and noun',
  'a. & adv.': 'adjective and adverb',
  'a. & pron.': 'adjective and pronoun',
  'a. & p. p.': 'adjective and past participle',
  'a. & vb. n.': 'adjective and verbal noun',
  'a., adv., & n.': 'adjective, adverb, and noun',
  'adv. & a.': 'adverb and adjective',
  'adv. & conj.': 'adverb and conjunction',
  'adv. & prep.': 'adverb and preposition',
  'adj. & adv.': 'adjective and adverb',
  'adj. prenom.': 'adjective, prenominal',
  'prep.': 'preposition',
  'prep. & adv.': 'preposition and adverb',
  'pron.': 'pronoun',
  'pron. & a.': 'pronoun and adjective',
  'pron. pl.': 'pronoun, plural',
  'conj.': 'conjunction',
  'interj.': 'interjection',
  'interj. & n.': 'interjection and noun',
  'pref.': 'prefix',
  'prefix.': 'prefix',
  'suff.': 'suffix',
  'imp.': 'imperfect',
  'imp. & p. p.': 'imperfect and past participle',
  'strong imp.': 'strong imperfect',
  'obs. imp.': 'obsolete imperfect',
  'p. p.': 'past participle',
  'p. p. & a.': 'past participle and adjective',
  'p. p. o a.': 'past participle and adjective',
  'p. a.': 'past participle (adjectival)',
  'p. pr.': 'present participle',
  'p. pr. & a.': 'present participle and adjective',
  'p. pr. & vb. n.': 'present participle and verbal noun',
  'p. a. & vb. n.': 'past participle and verbal noun',
  'vb. n.': 'verbal noun',
  'pred. a.': 'predicate adjective',
  'pred. adj.': 'predicate adjective',
  'pr. a.': 'present (adjectival)',
  'pr. n.': 'proper noun',
  'prop. n.': 'proper noun',
  'prop. n. pl.': 'proper noun, plural',
  'prop. a.': 'proper adjective',
  'prop. adj.': 'proper adjective',
  'prop. v. t.': 'proper transitive verb',
  'peop. n.': 'people, proper noun',
  'compar.': 'comparative',
  'phr.': 'phrase',
  'pl.': 'plural',
  '3d pers. sing. pres.': 'third person singular present',
  '2d pers. sing. pres.': 'second person singular present',
  'n': 'noun',
  'a & n.': 'adjective and noun',
};

export function expandPos(pos: string): string | null {
  return EXPANSIONS[pos] ?? null;
}
